### ISSUE TITLE
Tracker didn't update properly

### ISSUE THREAD

**Issue by hanahaneull** [nekomangaorg/Neko#1586]
### Steps to reproduce

1. Read manga that you never read + tracked (Make sure the manga are completed and have `[END]` tag)
2. Speedrun that shit
3. Now check the tracker

### Expected behavior

All tracker should mark the series as completed and set `Finished reading date` on tracker.

### Actual behavior

Currently only Anilist that mark the series as completed and set `Finished reading date`.
While MAL didn't update both reading status and `Finished reading date`.
MDList didn't update reading status.

Note: Other tracker are untested

### Neko version

2.14.0

### Android version

Android 11

### Device

Infinix X6812B

### Other details

![Screenshot_20231031-031332](https://github.com/CarlosEsco/Neko/assets/48522963/1de086e4-83d8-4f6d-9556-dfb66101ac3e)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/docs/guides/troubleshooting/).
- [X] I have updated the app to the newest version **[Latest](https://github.com/CarlosEsco/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by mods-hd** [comment]
Checked this on a current main build (345496edf, Pixel 6 emulator, Android 16). Added a completed two-chapter series (Tabun Kanojo wa Datsuzei Shiteru), tracked it on MangaDex as Reading and on MAL as Plan to Read, then read both chapters in the reader. After the last page the app posted `completed` to MangaDex (`POST /manga/{id}/status`) and updated the MAL list entry (`PUT /v2/manga/164639/my_list_status`). The tracking sheet shows both as Completed with the MAL start and finish dates set to today, and both sites show it as Completed. The fix is #3394, which is in 3.7.3 and later, so this one can probably be closed.
