### ISSUE TITLE
Improve manga tracking information.

### ISSUE THREAD

**Issue by Vlravyn** [nekomangaorg/Neko#1832]
### Describe your suggested feature

Right now, when tracking the manga on MAL, AniList etc. through the app, you have to update the the chapters read and score by scrolling. But sometimes MangaDex does not have all the chapters available for the manga, so we use alternative websites to read the manga. Updating it through the app becomes hard as you might have to scroll down a lot.

I feel like you should be able to input the chapter number to update it.

As this might be a issue for the manga scores because different websites have different scoring methods, maybe let us choose the default value the scroll will start from(for example, it should start at 7 instead of 0).

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have checked through the app settings for my feature.
- [X] I will fill out all of the requested information in this form.
